"""
Read a resolved CIQ template Excel file and return structured data.

The file must have been generated by generate_ciq_template.py,
opened in Excel with CIQ plugin, and saved after formulas resolved.

We read from the _RowMap sheet to know which row contains which variable,
then read column D (resolved values) from the CIQ_Data sheet.
"""

from __future__ import annotations

from datetime import datetime, timedelta
from pathlib import Path

import openpyxl


def read_ciq_template(file_path: str | Path) -> dict:
    """
    Read a resolved CIQ template and return structured data.

    Returns:
        {
            "ticker": str,
            "annual": {fy_offset: {variable: value}},
            "quarterly": {fq_offset: {variable: value}},
            "current": {variable: value},
            "period_dates": {variable: value},
        }
    """
    wb = openpyxl.load_workbook(str(file_path), data_only=True)

    # Read ticker from B1
    ws_data = wb["CIQ_Data"]
    ticker = str(ws_data["B1"].value or "").strip()

    # Read row map
    ws_map = wb["_RowMap"]
    row_map = []
    for r in range(2, ws_map.max_row + 1):
        row_num = ws_map.cell(r, 1).value
        variable = ws_map.cell(r, 2).value
        period = ws_map.cell(r, 3).value
        mnemonic = ws_map.cell(r, 4).value
        if row_num and variable:
            row_map.append({
                "row": int(row_num),
                "variable": str(variable),
                "period": str(period),
                "mnemonic": str(mnemonic or ""),
            })

    # Read resolved values from column D of CIQ_Data
    annual: dict[int, dict[str, float | str | None]] = {}
    quarterly: dict[int, dict[str, float | str | None]] = {}
    current: dict[str, float | str | None] = {}
    period_dates: dict[str, str | None] = {}

    # Expense-type fields: CIQ returns negative, Damodaran uses positive (absolute value)
    _EXPENSE_FIELDS = {"interest_expense", "capex", "d_a", "operating_lease_expense"}

    for entry in row_map:
        row = entry["row"]
        variable = entry["variable"]
        period = entry["period"]

        raw_val = ws_data.cell(row, 4).value  # Column D = resolved value
        value = _parse_value(raw_val)

        # Normalize expense-type fields to absolute value (Damodaran convention)
        if variable in _EXPENSE_FIELDS and isinstance(value, (int, float)):
            value = abs(value)

        # Geographic segments: period is like "rank_1", "rank_2" ... collect separately
        if variable.startswith("geo_seg_"):
            current.setdefault("_geo_seg_raw", {})[variable] = value
            continue

        if variable.startswith("period_date_"):
            formatted = _format_date(raw_val)
            # Store by variable name, also by FY offset for per-year dates
            if "FY-" in period:
                fy_off = period.split("FY-")[1]
                period_dates[f"period_date_annual_fy{fy_off}"] = formatted
                if fy_off == "0":
                    period_dates["period_date_annual"] = formatted
            elif "FQ-" in period:
                period_dates["period_date_quarterly"] = formatted
            else:
                period_dates[variable] = formatted
        elif period == "current":
            current[variable] = value
        elif "FQ-" in period:
            q_offset = int(period.split("FQ-")[1])
            if q_offset not in quarterly:
                quarterly[q_offset] = {}
            quarterly[q_offset][variable] = value
        elif "FY-" in period:
            fy_offset = int(period.split("FY-")[1])
            if fy_offset not in annual:
                annual[fy_offset] = {}
            annual[fy_offset][variable] = value

    wb.close()

    # R&D fallback: if r_and_d_expense is zero/null, use r_and_d_expense_fn
    for dataset in [annual, quarterly]:
        for offset, data in dataset.items():
            primary = data.get("r_and_d_expense")
            fallback = data.get("r_and_d_expense_fn")
            if (primary is None or primary == 0) and fallback and fallback != 0:
                data["r_and_d_expense"] = fallback
            # Clean up the fallback key — downstream code doesn't need it
            data.pop("r_and_d_expense_fn", None)

    # Post-process geographic segments into a clean list.
    # Raw form: {"geo_seg_name_1": "China", "geo_seg_rev_1": 15901, ...}
    # Clean form: [{"rank": 1, "name": "China", "revenue": 15901, "pct": 0.23}, ...]
    # Filters zero-revenue rows and common corporate/unallocated label patterns.
    _JUNK_LABELS = (
        "headquarters", "corporate", "unallocated", "eliminations",
        "inter-segment", "intersegment", "restructuring", "finance income",
        "finance costs", "finance expense", "hq",
    )
    geo_segments = []
    raw_geo = current.pop("_geo_seg_raw", {}) or {}
    if raw_geo:
        for rank in range(1, 11):
            name = raw_geo.get(f"geo_seg_name_{rank}")
            rev = raw_geo.get(f"geo_seg_rev_{rank}")
            if not isinstance(name, str) or not name.strip():
                continue
            if not isinstance(rev, (int, float)) or rev <= 0:
                continue
            low = name.lower()
            if any(j in low for j in _JUNK_LABELS):
                continue
            geo_segments.append({"rank": rank, "name": name.strip(), "revenue": float(rev)})
        # Compute percentage of total kept revenue
        total_rev = sum(s["revenue"] for s in geo_segments)
        if total_rev > 0:
            for s in geo_segments:
                s["pct"] = s["revenue"] / total_rev

    return {
        "ticker": ticker,
        "annual": annual,
        "quarterly": quarterly,
        "current": current,
        "period_dates": period_dates,
        "geo_segments": geo_segments,
    }


def _format_date(raw) -> str | None:
    """Convert Excel cell value (datetime, serial number, or string) to 'Jan 31, 2026' format."""
    if raw is None:
        return None
    # openpyxl may return a datetime object
    if isinstance(raw, datetime):
        return raw.strftime("%b %d, %Y")
    # Excel serial number (float or int)
    if isinstance(raw, (int, float)):
        n = float(raw)
        if 30000 < n < 60000:  # plausible Excel serial date range
            excel_epoch = datetime(1899, 12, 30)
            d = excel_epoch + timedelta(days=int(round(n)))
            return d.strftime("%b %d, %Y")
    # String that might be a date
    s = str(raw).strip()
    if not s:
        return None
    # Try parsing numeric string as serial
    try:
        n = float(s)
        if 30000 < n < 60000:
            excel_epoch = datetime(1899, 12, 30)
            d = excel_epoch + timedelta(days=int(round(n)))
            return d.strftime("%b %d, %Y")
    except ValueError:
        pass
    # Try parsing as date string
    try:
        d = datetime.fromisoformat(s.split(" ")[0])
        return d.strftime("%b %d, %Y")
    except (ValueError, IndexError):
        pass
    return s


def _parse_value(raw) -> float | str | None:
    """Parse a cell value into float, string, or None."""
    if raw is None:
        return None
    if isinstance(raw, (int, float)):
        return float(raw)
    s = str(raw).strip()
    if not s or s in ("N/A", "#N/A", "NA", "#VALUE!", "#REF!", "#NAME?"):
        return None
    if "GETTING" in s.upper() or "LOADING" in s.upper():
        return None  # formula not yet resolved
    # Try parsing as number
    try:
        return float(s.replace(",", ""))
    except ValueError:
        return s  # return as string (e.g., currency code "USD")
